### ISSUE TITLE
Lawo vsmGear & L-S-B panels : protocols

### ISSUE THREAD

**Issue by yboujraf** [borealsystems/Director#5]
Dear @monoxane 

I have seen that you mentioned that you are able to control Lawo vsmGear & L-S-B panels.

that's sound good.

Would you like to share which is the protocol you are used for this ?

I have tried with Ember+ to connect on the vsmGear (LBP, GPIOBOX, COMMSERVER, ...) but nothing.

Thanks if you could share the informations.

Best Regards,
Youssef

**Comment by monoxane** [comment]
I am not currently able to control them, I intend to MITM and reverse engineer the protocol for them to integrate into my orchestration suite, nothing is currently available and likely won’t be for quite some time.

**Comment by yboujraf** [comment]
Thanks
