### ISSUE TITLE
yarn build problem

### ISSUE THREAD

**Issue by booguiseb** [borealsystems/Director#7]
hi, 

i'm trying to build with yarn but i get this error 👍 

 src/core does not exist

MacBook-Pro-3:Director b-kopterlabs$ yarn run build
yarn run v1.22.4
$ rm -rf ./dist && yarn run build-core && yarn run build-ui
$ babel src/core -d dist/core
babel:
  src/core does not exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MacBook-Pro-3:Director b-kopterlabs$

**Comment by monoxane** [comment]
I use yarn workspaces with several packages within this monorepo, development instructions for each package are in their respective readmes (under packages/<package>/), but basically consist of `yarn workspace <package> run dev`

Also it doesn't do a whole lot right now so don't expect much :)

**Comment by booguiseb** [comment]
Hi Oliver,


Your project looks really interesting . I’m working for broadcast company myself and facing problems to interface different equipment all the time.
I hope you’ll succeed on your project.

Right now, I can’t do or try anything, yarn give me some errors all the time !

Thanks

Seb

**Comment by monoxane** [comment]
Yeap its definitely not ready for use at all, if you watch the project for releases only you'll get notified when a stable beta binary comes out you can test.
